spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://172.16.54.76/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

server:
    context-path: /shell
#logging:
#  pattern:
#    console: "%d  ----------  %msg%n"
#  path: D:\logs
#  file: D:\logs\shell.log
#  level:
#    com.weixin.ShellApplicationTests: debug